### ISSUE TITLE
Licence - classpath exception

### ISSUE THREAD

**Issue by arkadiusz-ark** [himamis/jlatexmath-multiplatform#7]
I'd like to ask if you would allow to add "classpath exception" to the GPLv2 licence of ReTeX.

Currently using ReTeX with other libraries released under Apache, BSD-style and proprietary licences is not allowed, because it creates combined work and all code must be released under GPL. The purpose of "classpath exception" is to allow other projects to link your library in unchanged form without being released under the GPL themself. Any modifications to the library code still would have to be distributed under GPL (https://en.wikipedia.org/wiki/GPL_linking_exception).

I know that ReTeX is based on the clone of JLaTeXMath, which is a clone of JMathTeX. Developers of JMathTeX and JLaTeXMath agreed to add "classpath exception" to JLaTeXMath. Since yesterday JLaTeXMath is licenced under GPLv2 with "classpath exception". (See discussion here: http://forge.scilab.org/index.php/p/jlatexmath/issues/1566/ and github https://github.com/opencollab/jlatexmath).

So, would you give permission to add "classpath exception" to ReTeX licence?

**Comment by himamis** [comment]
Sure, I have nothing against this exception. Please create a pull request with the modifications needed.

**Comment by himamis** [comment]
#8 has been merged.
